In [1]:
import numpy as np

In [2]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [3]:
x, y

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [4]:
x.shape, y.shape

((2, 2), (2, 2))

In [5]:
# Linear Algebra
# 1 
# det(A)=(1)(4)−(2)(3)=4−6=−2
det = np.linalg.det(x)
det

-2.0000000000000004

In [6]:
# 2
# dot product
dotp = np.dot(x, y)
dotp

array([[19, 22],
       [43, 50]])

In [7]:
# 3
# transpose x*T
trs = np.transpose(x)
trs

array([[1, 3],
       [2, 4]])

In [8]:
# 4
# inverse of a matrix 
inverse = np.linalg.inv(y)
inverse

array([[-4. ,  3. ],
       [ 3.5, -2.5]])

In [9]:
# 5
# Eigenvalues and Eigenvectors
eigen = np.linalg.eig(x)
eigen

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [10]:
# Calculus
# 6
# Numerical derivative 
x = np.array([0, 0.5, 1, 1.5])  
y = x ** 2
dy_dx = np.gradient(y, x)
print("x values:", x)
print("f(x) values:", y)
print("Numerical derivative dy/dx:", dy_dx)

x values: [0.  0.5 1.  1.5]
f(x) values: [0.   0.25 1.   2.25]
Numerical derivative dy/dx: [0.5 1.  2.  2.5]


In [11]:
# 7
# sin, cos...
z = np.sin(x)
sin_z = np.sin(x)
cos_z = np.cos(x)
tan_z = np.tan(x)
sin_z, cos_z, tan_z

(array([0.        , 0.47942554, 0.84147098, 0.99749499]),
 array([1.        , 0.87758256, 0.54030231, 0.0707372 ]),
 array([ 0.        ,  0.54630249,  1.55740772, 14.10141995]))

In [14]:
# 8
# integral(Simpson's rule)
from scipy.integrate import simps
a = np.array([0, 1, 2, 3, 4]) 
def f(x):
    return x ** 2

b = f(a)  #0,1,4,9,16

integral = simps(b, a)
integral

/var/folders/1p/5bfjw1dn3hv433xj4740231w0000gn/T/ipykernel_78407/2766318258.py:10: DeprecationWarning: 'scipy.integrate.simps' is deprecated in favour of 'scipy.integrate.simpson' and will be removed in SciPy 1.14.0
  integral = simps(b, a)


21.333333333333332

In [16]:
# 9
# Natural logarithm
natural_log = np.log(a)
natural_log

/var/folders/1p/5bfjw1dn3hv433xj4740231w0000gn/T/ipykernel_78407/2027855832.py:2: RuntimeWarning: divide by zero encountered in log
  natural_log = np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [17]:
# 10
# Exponential Function
c = np.sin(a)
exp_c = np.exp(c)
exp_c

array([1.        , 2.31977682, 2.48257773, 1.15156284, 0.46916419])

In [19]:
# Statistics
# 11
# the middle value in a sorted array
median = np.median(a)
median

2.0

In [22]:
# 12
# average value of all the elements in the array
values = np.array([23, 45, 87, 12, 90])
mean_value = np.mean(values)
mean_value

51.4

In [23]:
# 13
# Data Range (Max - Min)
range = np.ptp(values)
range

78

In [24]:
# 14
# x'th percentile of the array
perc = np.percentile(values, 25)
perc

23.0

In [28]:
# 15
# Covariance of two variables
data1 = np.array([2, 4, 6, 8])
data2 = np.array([1, 3, 2, 5])

cov_matrix = np.cov(data1, data2)
covariance = cov_matrix[0, 1]
print("Covariance between data1 and data2:", covariance)
cov_matrix


Covariance between data1 and data2: 3.6666666666666665


array([[6.66666667, 3.66666667],
       [3.66666667, 2.91666667]])